[package]
name = "WPEHost"
version = "0.1.0"
edition = "2021"

[dependencies]
thunder_rs = {git ="https://github.com/rdkcentral/thunder_rs.git", branch="main"}
libloading = "0.7.3"
byteorder = "1.4.3"
